# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.cache/wt [current_project]
set_property parent.project_path D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo d:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.srcs/sources_1/new/reg48.vhd
  D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.srcs/sources_1/new/adder.vhd
  D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.srcs/sources_1/new/multiplier.vhd
  D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.srcs/sources_1/new/truncator.vhd
  D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.srcs/sources_1/new/reg.vhd
  D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.srcs/sources_1/new/fir.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files D:/Users/Kevin/Documents/VHDL/fir-filter/fir_retimed/fir_retimed.srcs/constrs_1/new/timing.xdc]


synth_design -top fir -part xc7z020clg484-1


write_checkpoint -force -noxdef fir.dcp

catch { report_utilization -file fir_utilization_synth.rpt -pb fir_utilization_synth.pb }
